lib/twitter/rest/users.rb
spec/twitter/rest/users_spec.rb

This endpoint's deprecation [was announced](https://twittercommunity.com/t/deprecation-of-account-update-profile-colors/28692) in mid-December and it appears to have been removed, as the [documentation is no longer accessable](https://dev.twitter.com/rest/reference/post/account/update_profile_colors)

remove Twitter::REST::Users#update_profile_colors

---

lib/twitter/null_object.rb
spec/twitter/null_object_spec.rb

Right after we upgraded to Rails 4.1, we started noticing periodic `SystemStackErrors` being raised by our application when performing and rendering results from `Twitter::REST::Client#search`. This appears to be caused by an interaction between `Twitter::NullObject` and `ActiveSupport::JSON::Encoding::JSONGemEncoder#jsonify`, where:
```ruby
null_attr = Twitter::NullObject.new
ActiveSupport::JSON.encode(null_attr)
```
results in an infinite loop:
```ruby
ActiveSupport::JSON::Encoding::JSONGemEncoder:79 - jsonify
Twitter::NullObject::GeneratedMethods:90 - method_missing
Twitter::NullObject::GeneratedMethods:27 - method_missing
ActiveSupport::JSON::Encoding::JSONGemEncoder:79 - jsonify
Twitter::NullObject::GeneratedMethods:90 - method_missing
Twitter::NullObject::GeneratedMethods:27 - …
```

Attempting to json-encode a Twitter::NullObject with ActiveSupport results in SystemStackError

---

lib/twitter/null_object.rb

I bundled directly from github and started testing out the change, but it turns out that ActiveSupport::JSON passes an options argument to as_json.  I should have known, given most as_json definitions accept an optional argument.  Super sorry about this one -- I should have fully tested this before submitting a PR. I've made this change on my local copy of the gem, and I now get the following output:
```ruby
irb(main):001:0> null_attr = Twitter::NullObject.new
=> <null>
irb(main):002:0> ActiveSupport::JSON.encode(null_attr)
=> "\"null\""
```

as_json is frequently called with an options hash

---

examples/Configuration.md
lib/twitter/rest/request.rb
lib/twitter/streaming/client.rb
spec/twitter/rest/request_spec.rb
spec/twitter/streaming/client_spec.rb

@sferik this is pending some testing (see #639), but assuming all goes well, this should be good to merge. Thankfully, it was fairly easy to add support in both places. 
Note: I needed to disable rubocop's ClassLength check on `Twitter::REST::Request`. I hope that's ok. I tried reducing by using ternary operators in a few places (which I typically don't like to do), but couldn't squeeze it down to <100. It seems like there could be an opportunity to reduce the number of lines once `http.rb` supports multipart requests.

add proxy support to REST and Streaming clients

---

lib/twitter/tweet.rb
spec/twitter/tweet_spec.rb

Added `alias_method` to `Tweet` class.
It's for get to "retweet with comment" as api result.

Add methods to get to parameters of quoted tweet.

---

lib/twitter/rest/direct_messages.rb

Twitter has [announced API changes](https://twittercommunity.com/t/removing-the-140-character-limit-from-direct-messages/41348) related to the removal of the 140 character limitation

Document 140 character limitation removal for Direct Messages

---

lib/twitter/streaming/connection.rb
spec/twitter/streaming/connection_spec.rb

While developing https://github.com/logstash-plugins/logstash-input-twitter/pull/29 I encountered some issues with this gem I tried to fix in this PR. I will try to summarize them here in benefit of a full context when reviewing this pr.
* httprb request object has changed it behaviour in recent versions, if you use ```request.uri.port``` it will return the port, but if the port is one of the standard ones, like ```443``` for ssl it will return nill. This is an issue breaking the connection as it's implemented in the ```Streaming::Connection``` class.
* If using a proxy, ```request.uri.host``` and ```request.uri.port``` will not be proxy aware, you should use ```request.socket_host``` and ```request.socket_port```.
* Forcing to connect with a proxy over a SSL connection has shown …

Fix proxy support

---

lib/twitter/streaming/client.rb

There is a built-in command for making a form/encoded parameters in Ruby. If you don't want use the built-in command, which accpets a Hash object and coverts it to form/encoded parameters, you should use `URI.encode_www_form_component` method.
Failed test case in the current version:
```ruby
require 'twitter'
client = Twitter::Streaming::Client.new do |config|
config.consumer_key        = 'YOUR_CONSUMER_KEY'
config.consumer_secret     = 'YOUR_CONSUMER_SECRET'
config.access_token        = 'YOUR_ACCESS_TOKEN'
config.access_token_secret = 'YOUR_ACCESS_SECRET'
end
filter_params = {
:track => ':),:-),: ),:D,=),:(,:-(,: (,:/,:-/,=(,(:,):,)-:,(-:,( :,) :,:-D,:-|,:|,|:,|-:',
:language => 'es'
}
client.filter(filter_params) do |object|
puts object.text if object.is_a?(Twitter::Tweet)
end
```

Use built-in command to make form parameters

---

lib/twitter/profile.rb

Profile urls used to be strings.  Then they were URI::parse'd to return URI's.  URI only supports ascii strings, so URI.encode was quickly added so unicode urls didn't blow up.  
Then URI was switched for Addressible, which handles unicode just fine.  Can we remove the URI.encode to keep unicode urls?
This change does not break any specs.

Remove the encoding of profile urls

---

Rakefile
lib/twitter/rest/tweets.rb
spec/twitter/rest/tweets_spec.rb

Looks like Twitter recently added this endpoint. 
https://dev.twitter.com/rest/reference/post/statuses/unretweet/%3Aid
A couple quick notes:
* I opted not to implement the bang method since this endpoint is fairly passive. If you haven't retweeted the endpoint, it just returns the tweet itself (basically implememting statuses/show). I considered adding the bang method as an alias, but decided it was probably better not to implement it in case they change the behavior at some point.
* I wasn't thrilled about it, but I had to lower the yard coverage metric in order to get the build to fully pass.

add support for unretweet endpoint

---

.travis.yml
README.md
twitter.gemspec

Not sure if you're ready to drop Ruby 1.9 support or not, but I thought I'd get the ball rolling on this...

Upgrade http gem to ~> 2.0 (drops Ruby 1.9 support)

---

lib/twitter/error.rb

In https://dev.twitter.com/rest/reference/post/media/upload is following written:
```
Supported media types and filesize
Supported media types: jpg, png, gif, webp
Image file size must be <= 5 MB
The filesize limit above is enforced by the media upload endpoint. In addition, there is a separate product entity specific filesize limit which is applied when calling the Tweet creation (or similar) endpoints with media_id. For example, it is possible to upload a 5 MB image, but the Tweet creation endpoint requires images to be <= 3 MB.
```
Twitter returns a empty body and status code 413 when trying to upload a image which exceeds this size limit. This will lead to an unhelpful error for twitter gem users as it will lead to following:
```
irb(main):001:0> response_body = ''
=> "" …
```

Image upload with too big image

---

lib/twitter/client.rb
lib/twitter/rest/request.rb
spec/twitter/rest/request_spec.rb

Currently twitter gem users can not set a timeout for requests which could lead to stuck requests.
This fixes #791.

Use http's timeout api

---

lib/twitter/null_object.rb
spec/twitter/null_object_spec.rb

```
null = Twitter::NullOjbect.new
{ "null_object" => null }.to_json
```
In previous version, above code raises a TypeError:
TypeError: wrong argument type Twitter::NullObject (expected String)

Dump Twitter::NullObject as JSON properly

---

lib/twitter/streaming/event.rb

This makes it possible to get the Tweet object from a :quoted_tweet event.

Add quoted_tweet do tweet events

---

examples/README.md

An index page for the examples list, including subheadings. It wouldn't be a bad idea to add short summaries for each example.

Examples Index via README

---

lib/twitter/streaming/client.rb

As URI component of Ruby standard library only conforms with RFC3986 and
it doesn't encode `*` character and that leads to errors. It seems Addressable
library conforms with RFC3986, RFC3987 and RFC6570 and it encodes `*` character
as well.
Following test case will be failed in the current version and it returns
`Twitter::Error::Unauthorized` exception.
``` ruby
require 'twitter'
client = Twitter::Streaming::Client.new do |config|
config.consumer_key        = 'YOUR_CONSUMER_KEY'
config.consumer_secret     = 'YOUR_CONSUMER_SECRET'
config.access_token        = 'YOUR_ACCESS_TOKEN'
config.access_token_secret = 'YOUR_ACCESS_SECRET'
end
filter_params = {
:track => '(*^0^*)',
:language => 'es'
}
client.filter(filter_params) do |object|
puts object.text if object.is_a?(Twitter::Tweet)
end
```

Use addressable for building query string

---

lib/twitter/error.rb
spec/fixtures/already_retweeted.json

The old message is kept just in case it still occurs.
Here's my local workaround:
```ruby
Twitter::Error::FORBIDDEN_MESSAGES = Twitter::Error.send(:remove_const, :FORBIDDEN_MESSAGES).merge(
'You have already retweeted this tweet.' => Twitter::Error::AlreadyRetweeted
).freeze
```

Update the error message for Twitter::Error::AlreadyRetweeted

---

lib/twitter/streaming/connection.rb
spec/twitter/streaming/connection_spec.rb

Without correct TCP keepalive setup, the Twitter streaming client is prone to hang on long-lived connections. This is due to the nature of the protocol: a single request is made, then the client simply waits for data to read on a socket. Without keepalive, it may be indistinguishable to the client whether the connection has failed or there is simply no data to read.
These changes add the ability to set TCP keepalive providing the OS supports it. They also provide a set of sensible defaults to the keepalive for this implementation, while disabled by default.

[6-stable] Add TCP keepalive in Twitter::Streaming::Connection

---

lib/twitter/rest/request.rb

Addresses the repeated "[DEPRECATED] :mime_type option deprecated, use :content_type" warnings in the specs along with the issue mentioned in #881.

Fixes #881 Update to use content_type

---

CHANGELOG.md

Somehow, after this was merged into master, I do not see it in master. Maybe a force push accidentally deleted it?

Add 6.0.0 entry to changelog

---

lib/twitter/rest/direct_messages.rb
lib/twitter/rest/request.rb
spec/fixtures/direct_message_event.json
spec/twitter/rest/direct_messages_spec.rb

@sferik Here's a create method to go along with the list method, it would be great if we could add this to the next release.
btw, the rubocop rules from the cli are wanting trailing commas, while codeclimate doesn't want them.

Add create_direct_message_event method

---

lib/twitter/error.rb
spec/fixtures/already_retweeted.json

They changed the message again after #875, and the latest message I can observe in my Twitter API failure log is "You have already retweeted this Tweet."  The only difference is the last word which got capitalized. (sigh...)
So, I think it's time to drop the message-to-error table based on exact string match.

Follow Twitter API which again changed the message for already retweeted error

---

examples/Configuration.md

Current code doesn't work. I got following error:
```
/usr/src/app/vendor/bundle/ruby/2.2.0/gems/http-3.0.0/lib/http/chainable.rb:164:in `via': invalid HTTP proxy: {} (HTTP::RequestError)
from /usr/src/app/vendor/bundle/ruby/2.2.0/gems/twitter-6.2.0/lib/twitter/rest/request.rb:120:in `http_client'
from /usr/src/app/vendor/bundle/ruby/2.2.0/gems/twitter-6.2.0/lib/twitter/rest/request.rb:36:in `perform'
from /usr/src/app/vendor/bundle/ruby/2.2.0/gems/twitter-6.2.0/lib/twitter/search_results.rb:26:in `initialize'
from /usr/src/app/vendor/bundle/ruby/2.2.0/gems/twitter-6.2.0/lib/twitter/rest/search.rb:33:in `new'
from /usr/src/app/vendor/bundle/ruby/2.2.0/gems/twitter-6.2.0/lib/twitter/rest/search.rb:33:in `search'
from test.rb:10:in `<main>'
```
See:
- …

docs: Fix proxy setting sample code

---

lib/twitter/streaming/client.rb
lib/twitter/streaming/connection.rb
spec/twitter/streaming/connection_spec.rb

In this version, we can close stream as following:
```ruby
client = Twitter::Streaming::Client.new do |config|
end
t = Thread.new do
client.filter(track: keyword) do |object|
end
end
Signal.trap(:TERM) do
client.close
exit true
end
```

Support closing stream

---

lib/twitter/null_object.rb
spec/twitter/null_object_spec.rb

This makes consumption of the Twitter::NullObject easier in Rails projects.
Adds the following methods to Twitter::NullObject:
1. #presence
2. #present?
3. #blank?
This is a follow up to https://github.com/sferik/twitter/pull/764 with the requested changes.

Support ActiveSupport 'presence' methods on Twitter::NullObject

---

lib/twitter/rest/tweets.rb
spec/twitter/rest/request_spec.rb
spec/twitter/rest/tweets_spec.rb

Hello!
Awesome gem, thank you very much for your work! 
By method update_with_media can be uploaded only GIFs with size less than 5 megabytes, but Twitter allows to upload GIFs up to 15 megabytes by chunks. I've added support for this functionality and covered it with specs.

Big gifs chunk upload

---

lib/twitter/search_results.rb
spec/twitter/search_results_spec.rb

Hi!
Want to track limits while doing search requests to twitter API to looks like this:
```ruby
search = client.search('some query')
search.each do |tweet|
if search.rate_limit.remaining == 0
end
end
```

Track rate limit when searching tweets

---

lib/twitter/rest/direct_messages.rb
lib/twitter/rest/tweets.rb
lib/twitter/rest/upload_utils.rb
spec/twitter/rest/direct_messages_spec.rb

This PR completes #926 and adds a `create_direct_message_event_with_media` method to send a media alongside the DM's text, which is now possible thanks to the new API.

Add create_direct_message_event_with_media method

---

lib/twitter/rest/search.rb

- Motivation:
I was trying to use search tweet and I was getting tweets with truncate value, I found that twitter has updated the API and included a value `tweet_mode` that can get full tweet text.
To avoid another one have the same problem looking how to get full text I added the info on method comment.
[Doc Reference](https://developer.twitter.com/en/docs/tweets/tweet-updates)

Add info to search doc

---

lib/twitter/tweet.rb
spec/twitter/tweet_spec.rb

Recently while attempting to use `Twitter::REST::Tweets#statuses` (gem version 6.2.0) I noticed that tweets had no text returned when the `tweet_mode: extended` option is set. 
To test this, I wrote a small script:
```
tweet_ids = ["922321981", "979854652618375168"]
client.statuses(tweet_ids).each_with_index do |tweet, i|
puts "#{i+1}) Text: #{tweet.text}, Full Text: #{tweet.full_text}"
end
```
This will output the following (note that the second tweet is truncated):
```
1) Text: no, Full Text: no
2) Text: Guess what everyone? WE HIT 1000!! Thank you so much to all of my subscribers who helped us get here! Freya and I a… https://t.co/gL2HpqOgKt, Full Text: Guess what everyone? WE HIT 1000!! Thank you so much to all of my subscribers who helped us get here! Freya and I a… …
```

Replace text attribute with full_text if the extended Tweet has no text set

---

lib/twitter/rest/favorites.rb

ref: https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-favorites-list
>Specifies the number of records to retrieve. Must be less than or equal to 200; defaults to 20.
Hi, thank you for the very usuful gem!
This is update only for document.
---
ps. I'm using this gem at my own service, [favsearch](http://favsearch.chaspy.me). Thanks.

Update the maximum available favorites

---

lib/twitter/error.rb

Twitter returns the 420 status code when exceeding the connection limit for a user when using the Streaming API.
Fixes #930

Add 420 error

---

lib/twitter/base.rb
lib/twitter/user.rb

Hello,
Thanks for this gem!
`Addressable::URI.parse` will throw exceptions for URLs it thinks are invalid. The issue with this is that Addressable and Twitter do not agree on what qualifies as a valid URL. So a tweet can contain URL entities that Addressable believes are invalid. [`Addressable::URI.heuristic_parse`](https://github.com/sporkmonger/addressable/blob/f839fb28344567c792e148d7a74c529748455d11/lib/addressable/uri.rb#L150-L234) is Addressable's more lenient parser.
This will make it so any tainted URLs are parsed with `heuristic_parse`. This way there is less of a chance of encountering an `Addressable::URI::InvalidURIError` exception in the wild.
For example the tweet below contains the URL `http://suspicio\\.us/URL"`. Which Twitter recognizes as a URL so it shows up as an …

Use heuristic_parse for untrusted URLs.

---

spec/twitter/streaming/client_spec.rb

Typos in spec.
